project:
  type: website
  output-dir: docs

website:
  title: "Portfolio Marcos Palominos"
  navbar:
    left:
      - text: Portfolio Project
        href: portfolio-project/portfolio-project.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

